"""initial migration

Revision ID: 6492e7644857
Revises: 
Create Date: 2026-02-20 12:05:27.363540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6492e7644857'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_sort', 'events', ['sort_order'], unique=False)
    op.create_table('guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('rsvp_code', sa.String(length=8), nullable=False),
    sa.Column('rsvp_status', sa.Enum('PENDING', 'ATTENDING', 'NOT_ATTENDING', name='rsvpstatus'), nullable=False),
    sa.Column('plus_one_allowed', sa.Boolean(), nullable=False),
    sa.Column('plus_one_name', sa.String(length=255), nullable=True),
    sa.Column('plus_one_attending', sa.Boolean(), nullable=False),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('FR', 'EN', 'AR', name='language'), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_guest_name', 'guests', ['last_name', 'first_name'], unique=False)
    op.create_index('idx_guest_rsvp_status', 'guests', ['rsvp_status'], unique=False)
    op.create_index(op.f('ix_guests_group_name'), 'guests', ['group_name'], unique=False)
    op.create_index(op.f('ix_guests_rsvp_code'), 'guests', ['rsvp_code'], unique=True)
    op.create_index(op.f('ix_guests_rsvp_status'), 'guests', ['rsvp_status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.Enum('FR', 'EN', 'AR', name='language'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_guests_rsvp_status'), table_name='guests')
    op.drop_index(op.f('ix_guests_rsvp_code'), table_name='guests')
    op.drop_index(op.f('ix_guests_group_name'), table_name='guests')
    op.drop_index('idx_guest_rsvp_status', table_name='guests')
    op.drop_index('idx_guest_name', table_name='guests')
    op.drop_table('guests')
    op.drop_index('idx_event_sort', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
